### ISSUE TITLE
Implement simple MTTR (Mean time to restore) calculation based of a csv file

### ISSUE THREAD

**Issue by shadowman** [shadowman/omni-metric#3]
Implement a basic MTTR metric that can take input from a file. Use the CLI behaviour.

CSV format can be 'datetime', 'step_name', 'status'

**Comment by marabesi** [comment]
closed by 5cfdeaa9d22777ef93bd9ad658b545d671934979 2714fc410c7968605a265b1d836d0ad4c0c9356c and 573ea342697811c3b3919684bf074a6d168ac2e9
